/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel.impl;

import de.fraunhofer.ipa.deployment.deployModel.BuildRequirements;
import de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage;
import de.fraunhofer.ipa.deployment.deployModel.MultiValueList;
import de.fraunhofer.ipa.deployment.deployModel.ReqBuildDependencies;
import de.fraunhofer.ipa.deployment.deployModel.ReqDependencyRepositories;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Build Requirements</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.impl.BuildRequirementsImpl#getReqRosDistros <em>Req Ros Distros</em>}</li>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.impl.BuildRequirementsImpl#getReqTestRosDistros <em>Req Test Ros Distros</em>}</li>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.impl.BuildRequirementsImpl#getReqBuildDependencies <em>Req Build Dependencies</em>}</li>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.impl.BuildRequirementsImpl#getReqDependencyRepositories <em>Req Dependency Repositories</em>}</li>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.impl.BuildRequirementsImpl#getReqCMakeArgs <em>Req CMake Args</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BuildRequirementsImpl extends MinimalEObjectImpl.Container implements BuildRequirements
{
  /**
   * The cached value of the '{@link #getReqRosDistros() <em>Req Ros Distros</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReqRosDistros()
   * @generated
   * @ordered
   */
  protected MultiValueList reqRosDistros;

  /**
   * The cached value of the '{@link #getReqTestRosDistros() <em>Req Test Ros Distros</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReqTestRosDistros()
   * @generated
   * @ordered
   */
  protected MultiValueList reqTestRosDistros;

  /**
   * The cached value of the '{@link #getReqBuildDependencies() <em>Req Build Dependencies</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReqBuildDependencies()
   * @generated
   * @ordered
   */
  protected ReqBuildDependencies reqBuildDependencies;

  /**
   * The cached value of the '{@link #getReqDependencyRepositories() <em>Req Dependency Repositories</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReqDependencyRepositories()
   * @generated
   * @ordered
   */
  protected ReqDependencyRepositories reqDependencyRepositories;

  /**
   * The cached value of the '{@link #getReqCMakeArgs() <em>Req CMake Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReqCMakeArgs()
   * @generated
   * @ordered
   */
  protected MultiValueList reqCMakeArgs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BuildRequirementsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DeployModelPackage.Literals.BUILD_REQUIREMENTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MultiValueList getReqRosDistros()
  {
    return reqRosDistros;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReqRosDistros(MultiValueList newReqRosDistros, NotificationChain msgs)
  {
    MultiValueList oldReqRosDistros = reqRosDistros;
    reqRosDistros = newReqRosDistros;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DeployModelPackage.BUILD_REQUIREMENTS__REQ_ROS_DISTROS, oldReqRosDistros, newReqRosDistros);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReqRosDistros(MultiValueList newReqRosDistros)
  {
    if (newReqRosDistros != reqRosDistros)
    {
      NotificationChain msgs = null;
      if (reqRosDistros != null)
        msgs = ((InternalEObject)reqRosDistros).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DeployModelPackage.BUILD_REQUIREMENTS__REQ_ROS_DISTROS, null, msgs);
      if (newReqRosDistros != null)
        msgs = ((InternalEObject)newReqRosDistros).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DeployModelPackage.BUILD_REQUIREMENTS__REQ_ROS_DISTROS, null, msgs);
      msgs = basicSetReqRosDistros(newReqRosDistros, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DeployModelPackage.BUILD_REQUIREMENTS__REQ_ROS_DISTROS, newReqRosDistros, newReqRosDistros));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MultiValueList getReqTestRosDistros()
  {
    return reqTestRosDistros;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReqTestRosDistros(MultiValueList newReqTestRosDistros, NotificationChain msgs)
  {
    MultiValueList oldReqTestRosDistros = reqTestRosDistros;
    reqTestRosDistros = newReqTestRosDistros;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DeployModelPackage.BUILD_REQUIREMENTS__REQ_TEST_ROS_DISTROS, oldReqTestRosDistros, newReqTestRosDistros);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReqTestRosDistros(MultiValueList newReqTestRosDistros)
  {
    if (newReqTestRosDistros != reqTestRosDistros)
    {
      NotificationChain msgs = null;
      if (reqTestRosDistros != null)
        msgs = ((InternalEObject)reqTestRosDistros).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DeployModelPackage.BUILD_REQUIREMENTS__REQ_TEST_ROS_DISTROS, null, msgs);
      if (newReqTestRosDistros != null)
        msgs = ((InternalEObject)newReqTestRosDistros).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DeployModelPackage.BUILD_REQUIREMENTS__REQ_TEST_ROS_DISTROS, null, msgs);
      msgs = basicSetReqTestRosDistros(newReqTestRosDistros, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DeployModelPackage.BUILD_REQUIREMENTS__REQ_TEST_ROS_DISTROS, newReqTestRosDistros, newReqTestRosDistros));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReqBuildDependencies getReqBuildDependencies()
  {
    return reqBuildDependencies;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReqBuildDependencies(ReqBuildDependencies newReqBuildDependencies, NotificationChain msgs)
  {
    ReqBuildDependencies oldReqBuildDependencies = reqBuildDependencies;
    reqBuildDependencies = newReqBuildDependencies;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DeployModelPackage.BUILD_REQUIREMENTS__REQ_BUILD_DEPENDENCIES, oldReqBuildDependencies, newReqBuildDependencies);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReqBuildDependencies(ReqBuildDependencies newReqBuildDependencies)
  {
    if (newReqBuildDependencies != reqBuildDependencies)
    {
      NotificationChain msgs = null;
      if (reqBuildDependencies != null)
        msgs = ((InternalEObject)reqBuildDependencies).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DeployModelPackage.BUILD_REQUIREMENTS__REQ_BUILD_DEPENDENCIES, null, msgs);
      if (newReqBuildDependencies != null)
        msgs = ((InternalEObject)newReqBuildDependencies).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DeployModelPackage.BUILD_REQUIREMENTS__REQ_BUILD_DEPENDENCIES, null, msgs);
      msgs = basicSetReqBuildDependencies(newReqBuildDependencies, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DeployModelPackage.BUILD_REQUIREMENTS__REQ_BUILD_DEPENDENCIES, newReqBuildDependencies, newReqBuildDependencies));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReqDependencyRepositories getReqDependencyRepositories()
  {
    return reqDependencyRepositories;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReqDependencyRepositories(ReqDependencyRepositories newReqDependencyRepositories, NotificationChain msgs)
  {
    ReqDependencyRepositories oldReqDependencyRepositories = reqDependencyRepositories;
    reqDependencyRepositories = newReqDependencyRepositories;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DeployModelPackage.BUILD_REQUIREMENTS__REQ_DEPENDENCY_REPOSITORIES, oldReqDependencyRepositories, newReqDependencyRepositories);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReqDependencyRepositories(ReqDependencyRepositories newReqDependencyRepositories)
  {
    if (newReqDependencyRepositories != reqDependencyRepositories)
    {
      NotificationChain msgs = null;
      if (reqDependencyRepositories != null)
        msgs = ((InternalEObject)reqDependencyRepositories).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DeployModelPackage.BUILD_REQUIREMENTS__REQ_DEPENDENCY_REPOSITORIES, null, msgs);
      if (newReqDependencyRepositories != null)
        msgs = ((InternalEObject)newReqDependencyRepositories).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DeployModelPackage.BUILD_REQUIREMENTS__REQ_DEPENDENCY_REPOSITORIES, null, msgs);
      msgs = basicSetReqDependencyRepositories(newReqDependencyRepositories, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DeployModelPackage.BUILD_REQUIREMENTS__REQ_DEPENDENCY_REPOSITORIES, newReqDependencyRepositories, newReqDependencyRepositories));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MultiValueList getReqCMakeArgs()
  {
    return reqCMakeArgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReqCMakeArgs(MultiValueList newReqCMakeArgs, NotificationChain msgs)
  {
    MultiValueList oldReqCMakeArgs = reqCMakeArgs;
    reqCMakeArgs = newReqCMakeArgs;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DeployModelPackage.BUILD_REQUIREMENTS__REQ_CMAKE_ARGS, oldReqCMakeArgs, newReqCMakeArgs);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReqCMakeArgs(MultiValueList newReqCMakeArgs)
  {
    if (newReqCMakeArgs != reqCMakeArgs)
    {
      NotificationChain msgs = null;
      if (reqCMakeArgs != null)
        msgs = ((InternalEObject)reqCMakeArgs).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DeployModelPackage.BUILD_REQUIREMENTS__REQ_CMAKE_ARGS, null, msgs);
      if (newReqCMakeArgs != null)
        msgs = ((InternalEObject)newReqCMakeArgs).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DeployModelPackage.BUILD_REQUIREMENTS__REQ_CMAKE_ARGS, null, msgs);
      msgs = basicSetReqCMakeArgs(newReqCMakeArgs, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DeployModelPackage.BUILD_REQUIREMENTS__REQ_CMAKE_ARGS, newReqCMakeArgs, newReqCMakeArgs));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_ROS_DISTROS:
        return basicSetReqRosDistros(null, msgs);
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_TEST_ROS_DISTROS:
        return basicSetReqTestRosDistros(null, msgs);
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_BUILD_DEPENDENCIES:
        return basicSetReqBuildDependencies(null, msgs);
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_DEPENDENCY_REPOSITORIES:
        return basicSetReqDependencyRepositories(null, msgs);
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_CMAKE_ARGS:
        return basicSetReqCMakeArgs(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_ROS_DISTROS:
        return getReqRosDistros();
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_TEST_ROS_DISTROS:
        return getReqTestRosDistros();
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_BUILD_DEPENDENCIES:
        return getReqBuildDependencies();
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_DEPENDENCY_REPOSITORIES:
        return getReqDependencyRepositories();
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_CMAKE_ARGS:
        return getReqCMakeArgs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_ROS_DISTROS:
        setReqRosDistros((MultiValueList)newValue);
        return;
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_TEST_ROS_DISTROS:
        setReqTestRosDistros((MultiValueList)newValue);
        return;
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_BUILD_DEPENDENCIES:
        setReqBuildDependencies((ReqBuildDependencies)newValue);
        return;
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_DEPENDENCY_REPOSITORIES:
        setReqDependencyRepositories((ReqDependencyRepositories)newValue);
        return;
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_CMAKE_ARGS:
        setReqCMakeArgs((MultiValueList)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_ROS_DISTROS:
        setReqRosDistros((MultiValueList)null);
        return;
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_TEST_ROS_DISTROS:
        setReqTestRosDistros((MultiValueList)null);
        return;
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_BUILD_DEPENDENCIES:
        setReqBuildDependencies((ReqBuildDependencies)null);
        return;
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_DEPENDENCY_REPOSITORIES:
        setReqDependencyRepositories((ReqDependencyRepositories)null);
        return;
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_CMAKE_ARGS:
        setReqCMakeArgs((MultiValueList)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_ROS_DISTROS:
        return reqRosDistros != null;
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_TEST_ROS_DISTROS:
        return reqTestRosDistros != null;
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_BUILD_DEPENDENCIES:
        return reqBuildDependencies != null;
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_DEPENDENCY_REPOSITORIES:
        return reqDependencyRepositories != null;
      case DeployModelPackage.BUILD_REQUIREMENTS__REQ_CMAKE_ARGS:
        return reqCMakeArgs != null;
    }
    return super.eIsSet(featureID);
  }

} //BuildRequirementsImpl
