/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel.impl;

import de.fraunhofer.ipa.deployment.deployModel.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DeployModelFactoryImpl extends EFactoryImpl implements DeployModelFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static DeployModelFactory init()
  {
    try
    {
      DeployModelFactory theDeployModelFactory = (DeployModelFactory)EPackage.Registry.INSTANCE.getEFactory(DeployModelPackage.eNS_URI);
      if (theDeployModelFactory != null)
      {
        return theDeployModelFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new DeployModelFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DeployModelFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case DeployModelPackage.YAML: return createYaml();
      case DeployModelPackage.YAML_CONTENT: return createYamlContent();
      case DeployModelPackage.MONOLITHIC_IMPLEMENTATION_DESCRIPTION: return createMonolithicImplementationDescription();
      case DeployModelPackage.NEW_IMPLEMENTATION_ARTIFACT: return createNewImplementationArtifact();
      case DeployModelPackage.IMPLEMENTATION_ARTIFACT_DESCRIPTION: return createImplementationArtifactDescription();
      case DeployModelPackage.REUSE_IMPLEMENTATION_ARTIFACT: return createReuseImplementationArtifact();
      case DeployModelPackage.IMPLEMENTATION_ARTIFACT_ABSTRACT: return createImplementationArtifactAbstract();
      case DeployModelPackage.DEPLOYMENT_REQUIREMENTS: return createDeploymentRequirements();
      case DeployModelPackage.RESOURCE_REQUIREMENTS: return createResourceRequirements();
      case DeployModelPackage.RESOURCE_REQUIREMENT: return createResourceRequirement();
      case DeployModelPackage.REQ_OPERATING_SYSTEM: return createReqOperatingSystem();
      case DeployModelPackage.OPERATING_SYSTEM_TYPE_LIST: return createOperatingSystemTypeList();
      case DeployModelPackage.REQ_PROCESSOR_ARCHITECTURE: return createReqProcessorArchitecture();
      case DeployModelPackage.PROCESSOR_ARCHITECTURE_TYPE_LIST: return createProcessorArchitectureTypeList();
      case DeployModelPackage.REQ_ROS_DISTRO: return createReqRosDistro();
      case DeployModelPackage.ROS_DISTRO_LIST: return createRosDistroList();
      case DeployModelPackage.BUILD_REQUIREMENTS: return createBuildRequirements();
      case DeployModelPackage.REQ_BUILD_DEPENDENCIES: return createReqBuildDependencies();
      case DeployModelPackage.DEPENDENCY: return createDependency();
      case DeployModelPackage.LOCAL_PACKAGE: return createLocalPackage();
      case DeployModelPackage.GIT_PACKAGE: return createGitPackage();
      case DeployModelPackage.REQ_DEPENDENCY_REPOSITORIES: return createReqDependencyRepositories();
      case DeployModelPackage.APT_REPOSITORY_INSTANCE: return createAptRepositoryInstance();
      case DeployModelPackage.START_COMMANDS: return createStartCommands();
      case DeployModelPackage.LIST_START_COMMANDS: return createListStartCommands();
      case DeployModelPackage.STACK_IMPLEMENTATION_DESCRIPTION: return createStackImplementationDescription();
      case DeployModelPackage.PACKAGE_DESCRIPTION: return createPackageDescription();
      case DeployModelPackage.IMAGE_DESCRIPTION: return createImageDescription();
      case DeployModelPackage.IMAGE_TYPE_LIST: return createImageTypeList();
      case DeployModelPackage.IMAGE_VERSION_LIST: return createImageVersionList();
      case DeployModelPackage.REPOSITORY_DESCRIPTION: return createRepositoryDescription();
      case DeployModelPackage.REPOSITORY_SPEC: return createRepositorySpec();
      case DeployModelPackage.REPOSITORY: return createRepository();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case DeployModelPackage.IMPLEMENTATION_MODE_TYPE:
        return createImplementationModeTypeFromString(eDataType, initialValue);
      case DeployModelPackage.RESOURCE_REQ_TYPES:
        return createResourceReqTypesFromString(eDataType, initialValue);
      case DeployModelPackage.OPERATING_SYSTEM_TYPES:
        return createOperatingSystemTypesFromString(eDataType, initialValue);
      case DeployModelPackage.ROS_DISTRO:
        return createRosDistroFromString(eDataType, initialValue);
      case DeployModelPackage.PROCESSOR_ARCHITECTURE_TYPES:
        return createProcessorArchitectureTypesFromString(eDataType, initialValue);
      case DeployModelPackage.IMAGE_TYPES:
        return createImageTypesFromString(eDataType, initialValue);
      case DeployModelPackage.IMAGE_VERSION_TYPES:
        return createImageVersionTypesFromString(eDataType, initialValue);
      case DeployModelPackage.REPOSITORY_TYPES:
        return createRepositoryTypesFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case DeployModelPackage.IMPLEMENTATION_MODE_TYPE:
        return convertImplementationModeTypeToString(eDataType, instanceValue);
      case DeployModelPackage.RESOURCE_REQ_TYPES:
        return convertResourceReqTypesToString(eDataType, instanceValue);
      case DeployModelPackage.OPERATING_SYSTEM_TYPES:
        return convertOperatingSystemTypesToString(eDataType, instanceValue);
      case DeployModelPackage.ROS_DISTRO:
        return convertRosDistroToString(eDataType, instanceValue);
      case DeployModelPackage.PROCESSOR_ARCHITECTURE_TYPES:
        return convertProcessorArchitectureTypesToString(eDataType, instanceValue);
      case DeployModelPackage.IMAGE_TYPES:
        return convertImageTypesToString(eDataType, instanceValue);
      case DeployModelPackage.IMAGE_VERSION_TYPES:
        return convertImageVersionTypesToString(eDataType, instanceValue);
      case DeployModelPackage.REPOSITORY_TYPES:
        return convertRepositoryTypesToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Yaml createYaml()
  {
    YamlImpl yaml = new YamlImpl();
    return yaml;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public YamlContent createYamlContent()
  {
    YamlContentImpl yamlContent = new YamlContentImpl();
    return yamlContent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MonolithicImplementationDescription createMonolithicImplementationDescription()
  {
    MonolithicImplementationDescriptionImpl monolithicImplementationDescription = new MonolithicImplementationDescriptionImpl();
    return monolithicImplementationDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NewImplementationArtifact createNewImplementationArtifact()
  {
    NewImplementationArtifactImpl newImplementationArtifact = new NewImplementationArtifactImpl();
    return newImplementationArtifact;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImplementationArtifactDescription createImplementationArtifactDescription()
  {
    ImplementationArtifactDescriptionImpl implementationArtifactDescription = new ImplementationArtifactDescriptionImpl();
    return implementationArtifactDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReuseImplementationArtifact createReuseImplementationArtifact()
  {
    ReuseImplementationArtifactImpl reuseImplementationArtifact = new ReuseImplementationArtifactImpl();
    return reuseImplementationArtifact;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImplementationArtifactAbstract createImplementationArtifactAbstract()
  {
    ImplementationArtifactAbstractImpl implementationArtifactAbstract = new ImplementationArtifactAbstractImpl();
    return implementationArtifactAbstract;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeploymentRequirements createDeploymentRequirements()
  {
    DeploymentRequirementsImpl deploymentRequirements = new DeploymentRequirementsImpl();
    return deploymentRequirements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ResourceRequirements createResourceRequirements()
  {
    ResourceRequirementsImpl resourceRequirements = new ResourceRequirementsImpl();
    return resourceRequirements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ResourceRequirement createResourceRequirement()
  {
    ResourceRequirementImpl resourceRequirement = new ResourceRequirementImpl();
    return resourceRequirement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReqOperatingSystem createReqOperatingSystem()
  {
    ReqOperatingSystemImpl reqOperatingSystem = new ReqOperatingSystemImpl();
    return reqOperatingSystem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperatingSystemTypeList createOperatingSystemTypeList()
  {
    OperatingSystemTypeListImpl operatingSystemTypeList = new OperatingSystemTypeListImpl();
    return operatingSystemTypeList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReqProcessorArchitecture createReqProcessorArchitecture()
  {
    ReqProcessorArchitectureImpl reqProcessorArchitecture = new ReqProcessorArchitectureImpl();
    return reqProcessorArchitecture;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProcessorArchitectureTypeList createProcessorArchitectureTypeList()
  {
    ProcessorArchitectureTypeListImpl processorArchitectureTypeList = new ProcessorArchitectureTypeListImpl();
    return processorArchitectureTypeList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReqRosDistro createReqRosDistro()
  {
    ReqRosDistroImpl reqRosDistro = new ReqRosDistroImpl();
    return reqRosDistro;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RosDistroList createRosDistroList()
  {
    RosDistroListImpl rosDistroList = new RosDistroListImpl();
    return rosDistroList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BuildRequirements createBuildRequirements()
  {
    BuildRequirementsImpl buildRequirements = new BuildRequirementsImpl();
    return buildRequirements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReqBuildDependencies createReqBuildDependencies()
  {
    ReqBuildDependenciesImpl reqBuildDependencies = new ReqBuildDependenciesImpl();
    return reqBuildDependencies;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Dependency createDependency()
  {
    DependencyImpl dependency = new DependencyImpl();
    return dependency;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LocalPackage createLocalPackage()
  {
    LocalPackageImpl localPackage = new LocalPackageImpl();
    return localPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GitPackage createGitPackage()
  {
    GitPackageImpl gitPackage = new GitPackageImpl();
    return gitPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReqDependencyRepositories createReqDependencyRepositories()
  {
    ReqDependencyRepositoriesImpl reqDependencyRepositories = new ReqDependencyRepositoriesImpl();
    return reqDependencyRepositories;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AptRepositoryInstance createAptRepositoryInstance()
  {
    AptRepositoryInstanceImpl aptRepositoryInstance = new AptRepositoryInstanceImpl();
    return aptRepositoryInstance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StartCommands createStartCommands()
  {
    StartCommandsImpl startCommands = new StartCommandsImpl();
    return startCommands;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ListStartCommands createListStartCommands()
  {
    ListStartCommandsImpl listStartCommands = new ListStartCommandsImpl();
    return listStartCommands;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StackImplementationDescription createStackImplementationDescription()
  {
    StackImplementationDescriptionImpl stackImplementationDescription = new StackImplementationDescriptionImpl();
    return stackImplementationDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PackageDescription createPackageDescription()
  {
    PackageDescriptionImpl packageDescription = new PackageDescriptionImpl();
    return packageDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImageDescription createImageDescription()
  {
    ImageDescriptionImpl imageDescription = new ImageDescriptionImpl();
    return imageDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImageTypeList createImageTypeList()
  {
    ImageTypeListImpl imageTypeList = new ImageTypeListImpl();
    return imageTypeList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImageVersionList createImageVersionList()
  {
    ImageVersionListImpl imageVersionList = new ImageVersionListImpl();
    return imageVersionList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RepositoryDescription createRepositoryDescription()
  {
    RepositoryDescriptionImpl repositoryDescription = new RepositoryDescriptionImpl();
    return repositoryDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RepositorySpec createRepositorySpec()
  {
    RepositorySpecImpl repositorySpec = new RepositorySpecImpl();
    return repositorySpec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Repository createRepository()
  {
    RepositoryImpl repository = new RepositoryImpl();
    return repository;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ImplementationModeType createImplementationModeTypeFromString(EDataType eDataType, String initialValue)
  {
    ImplementationModeType result = ImplementationModeType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertImplementationModeTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ResourceReqTypes createResourceReqTypesFromString(EDataType eDataType, String initialValue)
  {
    ResourceReqTypes result = ResourceReqTypes.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertResourceReqTypesToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OperatingSystemTypes createOperatingSystemTypesFromString(EDataType eDataType, String initialValue)
  {
    OperatingSystemTypes result = OperatingSystemTypes.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertOperatingSystemTypesToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RosDistro createRosDistroFromString(EDataType eDataType, String initialValue)
  {
    RosDistro result = RosDistro.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertRosDistroToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessorArchitectureTypes createProcessorArchitectureTypesFromString(EDataType eDataType, String initialValue)
  {
    ProcessorArchitectureTypes result = ProcessorArchitectureTypes.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertProcessorArchitectureTypesToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ImageTypes createImageTypesFromString(EDataType eDataType, String initialValue)
  {
    ImageTypes result = ImageTypes.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertImageTypesToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ImageVersionTypes createImageVersionTypesFromString(EDataType eDataType, String initialValue)
  {
    ImageVersionTypes result = ImageVersionTypes.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertImageVersionTypesToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RepositoryTypes createRepositoryTypesFromString(EDataType eDataType, String initialValue)
  {
    RepositoryTypes result = RepositoryTypes.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertRepositoryTypesToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeployModelPackage getDeployModelPackage()
  {
    return (DeployModelPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static DeployModelPackage getPackage()
  {
    return DeployModelPackage.eINSTANCE;
  }

} //DeployModelFactoryImpl
