/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel.impl;

import de.fraunhofer.ipa.deployment.deployModel.AptRepositoryInstance;
import de.fraunhofer.ipa.deployment.deployModel.BuildRequirements;
import de.fraunhofer.ipa.deployment.deployModel.CIParameters;
import de.fraunhofer.ipa.deployment.deployModel.CISetting;
import de.fraunhofer.ipa.deployment.deployModel.CommonPropertyMultiValue;
import de.fraunhofer.ipa.deployment.deployModel.CommonPropertySingleValue;
import de.fraunhofer.ipa.deployment.deployModel.DependencyTypes;
import de.fraunhofer.ipa.deployment.deployModel.DeployModelFactory;
import de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage;
import de.fraunhofer.ipa.deployment.deployModel.DeploymentRequirements;
import de.fraunhofer.ipa.deployment.deployModel.GitPackage;
import de.fraunhofer.ipa.deployment.deployModel.GroupedProperties;
import de.fraunhofer.ipa.deployment.deployModel.ImageDescription;
import de.fraunhofer.ipa.deployment.deployModel.ImplementationArtifactAbstract;
import de.fraunhofer.ipa.deployment.deployModel.ImplementationArtifactDescription;
import de.fraunhofer.ipa.deployment.deployModel.ImplementationModeType;
import de.fraunhofer.ipa.deployment.deployModel.LocalPackage;
import de.fraunhofer.ipa.deployment.deployModel.MonolithicImplementationDescription;
import de.fraunhofer.ipa.deployment.deployModel.MultiMonolithicImplementationNameList;
import de.fraunhofer.ipa.deployment.deployModel.MultiMonolithicImplementationNameListBracket;
import de.fraunhofer.ipa.deployment.deployModel.MultiMonolithicImplementationNamePreList;
import de.fraunhofer.ipa.deployment.deployModel.MultiValueList;
import de.fraunhofer.ipa.deployment.deployModel.MultiValueListBracket;
import de.fraunhofer.ipa.deployment.deployModel.MultiValueListPreList;
import de.fraunhofer.ipa.deployment.deployModel.NewImplementationArtifact;
import de.fraunhofer.ipa.deployment.deployModel.PackageDescription;
import de.fraunhofer.ipa.deployment.deployModel.PropertyExpressType;
import de.fraunhofer.ipa.deployment.deployModel.Repository;
import de.fraunhofer.ipa.deployment.deployModel.RepositoryDescription;
import de.fraunhofer.ipa.deployment.deployModel.RepositorySpec;
import de.fraunhofer.ipa.deployment.deployModel.ReqBuildDependencies;
import de.fraunhofer.ipa.deployment.deployModel.ReqDependencyRepositories;
import de.fraunhofer.ipa.deployment.deployModel.ResourceRequirements;
import de.fraunhofer.ipa.deployment.deployModel.ReuseImplementationArtifact;
import de.fraunhofer.ipa.deployment.deployModel.StackImplementationDescription;
import de.fraunhofer.ipa.deployment.deployModel.Yaml;
import de.fraunhofer.ipa.deployment.deployModel.YamlContent;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DeployModelPackageImpl extends EPackageImpl implements DeployModelPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yamlEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass yamlContentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass monolithicImplementationDescriptionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass newImplementationArtifactEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass implementationArtifactDescriptionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass reuseImplementationArtifactEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass implementationArtifactAbstractEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass deploymentRequirementsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass resourceRequirementsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass propertyExpressTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass commonPropertySingleValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass commonPropertyMultiValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiValueListEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiValueListPreListEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiValueListBracketEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass buildRequirementsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass reqBuildDependenciesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dependencyTypesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass localPackageEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass gitPackageEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass reqDependencyRepositoriesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass aptRepositoryInstanceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stackImplementationDescriptionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass packageDescriptionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imageDescriptionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass repositoryDescriptionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass repositorySpecEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass repositoryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ciSettingEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiMonolithicImplementationNameListEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiMonolithicImplementationNamePreListEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiMonolithicImplementationNameListBracketEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ciParametersEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass groupedPropertiesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum implementationModeTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum booleanEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private DeployModelPackageImpl()
  {
    super(eNS_URI, DeployModelFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link DeployModelPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static DeployModelPackage init()
  {
    if (isInited) return (DeployModelPackage)EPackage.Registry.INSTANCE.getEPackage(DeployModelPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredDeployModelPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    DeployModelPackageImpl theDeployModelPackage = registeredDeployModelPackage instanceof DeployModelPackageImpl ? (DeployModelPackageImpl)registeredDeployModelPackage : new DeployModelPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theDeployModelPackage.createPackageContents();

    // Initialize created meta-data
    theDeployModelPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theDeployModelPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(DeployModelPackage.eNS_URI, theDeployModelPackage);
    return theDeployModelPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getYaml()
  {
    return yamlEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getYaml_Content()
  {
    return (EReference)yamlEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getYamlContent()
  {
    return yamlContentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getYamlContent_RootContent()
  {
    return (EReference)yamlContentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMonolithicImplementationDescription()
  {
    return monolithicImplementationDescriptionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMonolithicImplementationDescription_Type()
  {
    return (EAttribute)monolithicImplementationDescriptionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMonolithicImplementationDescription_Name()
  {
    return (EAttribute)monolithicImplementationDescriptionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMonolithicImplementationDescription_ImpRosmodel()
  {
    return (EAttribute)monolithicImplementationDescriptionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMonolithicImplementationDescription_Description()
  {
    return (EAttribute)monolithicImplementationDescriptionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMonolithicImplementationDescription_Mode()
  {
    return (EAttribute)monolithicImplementationDescriptionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMonolithicImplementationDescription_Branch()
  {
    return (EAttribute)monolithicImplementationDescriptionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMonolithicImplementationDescription_Implementation()
  {
    return (EReference)monolithicImplementationDescriptionEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNewImplementationArtifact()
  {
    return newImplementationArtifactEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNewImplementationArtifact_Location()
  {
    return (EAttribute)newImplementationArtifactEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNewImplementationArtifact_DeployRequirements()
  {
    return (EReference)newImplementationArtifactEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNewImplementationArtifact_ResourceRequirements()
  {
    return (EReference)newImplementationArtifactEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNewImplementationArtifact_BuildRequirements()
  {
    return (EReference)newImplementationArtifactEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNewImplementationArtifact_StartCommands()
  {
    return (EReference)newImplementationArtifactEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImplementationArtifactDescription()
  {
    return implementationArtifactDescriptionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImplementationArtifactDescription_Impl()
  {
    return (EReference)implementationArtifactDescriptionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getReuseImplementationArtifact()
  {
    return reuseImplementationArtifactEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getReuseImplementationArtifact_Lists()
  {
    return (EReference)reuseImplementationArtifactEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImplementationArtifactAbstract()
  {
    return implementationArtifactAbstractEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImplementationArtifactAbstract_ImportedNamespace()
  {
    return (EAttribute)implementationArtifactAbstractEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImplementationArtifactAbstract_Name()
  {
    return (EReference)implementationArtifactAbstractEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImplementationArtifactAbstract_StartCommands()
  {
    return (EReference)implementationArtifactAbstractEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeploymentRequirements()
  {
    return deploymentRequirementsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeploymentRequirements_Requirements()
  {
    return (EReference)deploymentRequirementsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getResourceRequirements()
  {
    return resourceRequirementsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getResourceRequirements_Requirements()
  {
    return (EReference)resourceRequirementsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPropertyExpressType()
  {
    return propertyExpressTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPropertyExpressType_Name()
  {
    return (EAttribute)propertyExpressTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCommonPropertySingleValue()
  {
    return commonPropertySingleValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCommonPropertySingleValue_Value()
  {
    return (EAttribute)commonPropertySingleValueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCommonPropertyMultiValue()
  {
    return commonPropertyMultiValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCommonPropertyMultiValue_Value()
  {
    return (EReference)commonPropertyMultiValueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMultiValueList()
  {
    return multiValueListEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMultiValueList_Values()
  {
    return (EAttribute)multiValueListEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMultiValueListPreList()
  {
    return multiValueListPreListEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMultiValueListBracket()
  {
    return multiValueListBracketEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBuildRequirements()
  {
    return buildRequirementsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBuildRequirements_ReqRosDistros()
  {
    return (EReference)buildRequirementsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBuildRequirements_ReqTestRosDistros()
  {
    return (EReference)buildRequirementsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBuildRequirements_ReqBuildDependencies()
  {
    return (EReference)buildRequirementsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBuildRequirements_ReqDependencyRepositories()
  {
    return (EReference)buildRequirementsEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBuildRequirements_ReqCMakeArgs()
  {
    return (EReference)buildRequirementsEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getReqBuildDependencies()
  {
    return reqBuildDependenciesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getReqBuildDependencies_Dependencies()
  {
    return (EReference)reqBuildDependenciesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDependencyTypes()
  {
    return dependencyTypesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLocalPackage()
  {
    return localPackageEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLocalPackage_Name()
  {
    return (EReference)localPackageEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGitPackage()
  {
    return gitPackageEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGitPackage_Name()
  {
    return (EAttribute)gitPackageEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGitPackage_Path()
  {
    return (EAttribute)gitPackageEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGitPackage_Visibility()
  {
    return (EAttribute)gitPackageEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getReqDependencyRepositories()
  {
    return reqDependencyRepositoriesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getReqDependencyRepositories_Children()
  {
    return (EReference)reqDependencyRepositoriesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAptRepositoryInstance()
  {
    return aptRepositoryInstanceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAptRepositoryInstance_Name()
  {
    return (EAttribute)aptRepositoryInstanceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAptRepositoryInstance_KeyLink()
  {
    return (EAttribute)aptRepositoryInstanceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAptRepositoryInstance_RepositoryPath()
  {
    return (EAttribute)aptRepositoryInstanceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAptRepositoryInstance_UpdateRosDep()
  {
    return (EAttribute)aptRepositoryInstanceEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStackImplementationDescription()
  {
    return stackImplementationDescriptionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStackImplementationDescription_Type()
  {
    return (EAttribute)stackImplementationDescriptionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStackImplementationDescription_Name()
  {
    return (EAttribute)stackImplementationDescriptionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStackImplementationDescription_ImpRosmodel()
  {
    return (EAttribute)stackImplementationDescriptionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStackImplementationDescription_Description()
  {
    return (EAttribute)stackImplementationDescriptionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStackImplementationDescription_Mode()
  {
    return (EAttribute)stackImplementationDescriptionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStackImplementationDescription_Impl()
  {
    return (EReference)stackImplementationDescriptionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPackageDescription()
  {
    return packageDescriptionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPackageDescription_Type()
  {
    return (EAttribute)packageDescriptionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPackageDescription_Name()
  {
    return (EAttribute)packageDescriptionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPackageDescription_ImageDescription()
  {
    return (EReference)packageDescriptionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPackageDescription_RepositoryDescription()
  {
    return (EReference)packageDescriptionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImageDescription()
  {
    return imageDescriptionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImageDescription_Types()
  {
    return (EReference)imageDescriptionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImageDescription_AppiledImplementations()
  {
    return (EReference)imageDescriptionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getImageDescription_ImageTags()
  {
    return (EReference)imageDescriptionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRepositoryDescription()
  {
    return repositoryDescriptionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRepositoryDescription_Spec()
  {
    return (EReference)repositoryDescriptionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRepositorySpec()
  {
    return repositorySpecEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRepositorySpec_Name()
  {
    return (EAttribute)repositorySpecEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRepositorySpec_Repository()
  {
    return (EReference)repositorySpecEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRepository()
  {
    return repositoryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRepository_Type()
  {
    return (EAttribute)repositoryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRepository_Path()
  {
    return (EAttribute)repositoryEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCISetting()
  {
    return ciSettingEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCISetting_Type()
  {
    return (EAttribute)ciSettingEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCISetting_Name()
  {
    return (EAttribute)ciSettingEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCISetting_CiTypes()
  {
    return (EReference)ciSettingEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCISetting_AppliedRepos()
  {
    return (EReference)ciSettingEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCISetting_ReqBranchPrefix()
  {
    return (EAttribute)ciSettingEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCISetting_CiParameters()
  {
    return (EReference)ciSettingEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMultiMonolithicImplementationNameList()
  {
    return multiMonolithicImplementationNameListEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMultiMonolithicImplementationNameList_Values()
  {
    return (EReference)multiMonolithicImplementationNameListEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMultiMonolithicImplementationNamePreList()
  {
    return multiMonolithicImplementationNamePreListEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMultiMonolithicImplementationNameListBracket()
  {
    return multiMonolithicImplementationNameListBracketEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCIParameters()
  {
    return ciParametersEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCIParameters_Type()
  {
    return (EAttribute)ciParametersEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCIParameters_Parameters()
  {
    return (EReference)ciParametersEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGroupedProperties()
  {
    return groupedPropertiesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGroupedProperties_Type()
  {
    return (EAttribute)groupedPropertiesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGroupedProperties_Properties()
  {
    return (EReference)groupedPropertiesEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getImplementationModeType()
  {
    return implementationModeTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getBOOLEAN()
  {
    return booleanEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeployModelFactory getDeployModelFactory()
  {
    return (DeployModelFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    yamlEClass = createEClass(YAML);
    createEReference(yamlEClass, YAML__CONTENT);

    yamlContentEClass = createEClass(YAML_CONTENT);
    createEReference(yamlContentEClass, YAML_CONTENT__ROOT_CONTENT);

    monolithicImplementationDescriptionEClass = createEClass(MONOLITHIC_IMPLEMENTATION_DESCRIPTION);
    createEAttribute(monolithicImplementationDescriptionEClass, MONOLITHIC_IMPLEMENTATION_DESCRIPTION__TYPE);
    createEAttribute(monolithicImplementationDescriptionEClass, MONOLITHIC_IMPLEMENTATION_DESCRIPTION__NAME);
    createEAttribute(monolithicImplementationDescriptionEClass, MONOLITHIC_IMPLEMENTATION_DESCRIPTION__IMP_ROSMODEL);
    createEAttribute(monolithicImplementationDescriptionEClass, MONOLITHIC_IMPLEMENTATION_DESCRIPTION__DESCRIPTION);
    createEAttribute(monolithicImplementationDescriptionEClass, MONOLITHIC_IMPLEMENTATION_DESCRIPTION__MODE);
    createEAttribute(monolithicImplementationDescriptionEClass, MONOLITHIC_IMPLEMENTATION_DESCRIPTION__BRANCH);
    createEReference(monolithicImplementationDescriptionEClass, MONOLITHIC_IMPLEMENTATION_DESCRIPTION__IMPLEMENTATION);

    newImplementationArtifactEClass = createEClass(NEW_IMPLEMENTATION_ARTIFACT);
    createEAttribute(newImplementationArtifactEClass, NEW_IMPLEMENTATION_ARTIFACT__LOCATION);
    createEReference(newImplementationArtifactEClass, NEW_IMPLEMENTATION_ARTIFACT__DEPLOY_REQUIREMENTS);
    createEReference(newImplementationArtifactEClass, NEW_IMPLEMENTATION_ARTIFACT__RESOURCE_REQUIREMENTS);
    createEReference(newImplementationArtifactEClass, NEW_IMPLEMENTATION_ARTIFACT__BUILD_REQUIREMENTS);
    createEReference(newImplementationArtifactEClass, NEW_IMPLEMENTATION_ARTIFACT__START_COMMANDS);

    implementationArtifactDescriptionEClass = createEClass(IMPLEMENTATION_ARTIFACT_DESCRIPTION);
    createEReference(implementationArtifactDescriptionEClass, IMPLEMENTATION_ARTIFACT_DESCRIPTION__IMPL);

    reuseImplementationArtifactEClass = createEClass(REUSE_IMPLEMENTATION_ARTIFACT);
    createEReference(reuseImplementationArtifactEClass, REUSE_IMPLEMENTATION_ARTIFACT__LISTS);

    implementationArtifactAbstractEClass = createEClass(IMPLEMENTATION_ARTIFACT_ABSTRACT);
    createEAttribute(implementationArtifactAbstractEClass, IMPLEMENTATION_ARTIFACT_ABSTRACT__IMPORTED_NAMESPACE);
    createEReference(implementationArtifactAbstractEClass, IMPLEMENTATION_ARTIFACT_ABSTRACT__NAME);
    createEReference(implementationArtifactAbstractEClass, IMPLEMENTATION_ARTIFACT_ABSTRACT__START_COMMANDS);

    deploymentRequirementsEClass = createEClass(DEPLOYMENT_REQUIREMENTS);
    createEReference(deploymentRequirementsEClass, DEPLOYMENT_REQUIREMENTS__REQUIREMENTS);

    resourceRequirementsEClass = createEClass(RESOURCE_REQUIREMENTS);
    createEReference(resourceRequirementsEClass, RESOURCE_REQUIREMENTS__REQUIREMENTS);

    propertyExpressTypeEClass = createEClass(PROPERTY_EXPRESS_TYPE);
    createEAttribute(propertyExpressTypeEClass, PROPERTY_EXPRESS_TYPE__NAME);

    commonPropertySingleValueEClass = createEClass(COMMON_PROPERTY_SINGLE_VALUE);
    createEAttribute(commonPropertySingleValueEClass, COMMON_PROPERTY_SINGLE_VALUE__VALUE);

    commonPropertyMultiValueEClass = createEClass(COMMON_PROPERTY_MULTI_VALUE);
    createEReference(commonPropertyMultiValueEClass, COMMON_PROPERTY_MULTI_VALUE__VALUE);

    multiValueListEClass = createEClass(MULTI_VALUE_LIST);
    createEAttribute(multiValueListEClass, MULTI_VALUE_LIST__VALUES);

    multiValueListPreListEClass = createEClass(MULTI_VALUE_LIST_PRE_LIST);

    multiValueListBracketEClass = createEClass(MULTI_VALUE_LIST_BRACKET);

    buildRequirementsEClass = createEClass(BUILD_REQUIREMENTS);
    createEReference(buildRequirementsEClass, BUILD_REQUIREMENTS__REQ_ROS_DISTROS);
    createEReference(buildRequirementsEClass, BUILD_REQUIREMENTS__REQ_TEST_ROS_DISTROS);
    createEReference(buildRequirementsEClass, BUILD_REQUIREMENTS__REQ_BUILD_DEPENDENCIES);
    createEReference(buildRequirementsEClass, BUILD_REQUIREMENTS__REQ_DEPENDENCY_REPOSITORIES);
    createEReference(buildRequirementsEClass, BUILD_REQUIREMENTS__REQ_CMAKE_ARGS);

    reqBuildDependenciesEClass = createEClass(REQ_BUILD_DEPENDENCIES);
    createEReference(reqBuildDependenciesEClass, REQ_BUILD_DEPENDENCIES__DEPENDENCIES);

    dependencyTypesEClass = createEClass(DEPENDENCY_TYPES);

    localPackageEClass = createEClass(LOCAL_PACKAGE);
    createEReference(localPackageEClass, LOCAL_PACKAGE__NAME);

    gitPackageEClass = createEClass(GIT_PACKAGE);
    createEAttribute(gitPackageEClass, GIT_PACKAGE__NAME);
    createEAttribute(gitPackageEClass, GIT_PACKAGE__PATH);
    createEAttribute(gitPackageEClass, GIT_PACKAGE__VISIBILITY);

    reqDependencyRepositoriesEClass = createEClass(REQ_DEPENDENCY_REPOSITORIES);
    createEReference(reqDependencyRepositoriesEClass, REQ_DEPENDENCY_REPOSITORIES__CHILDREN);

    aptRepositoryInstanceEClass = createEClass(APT_REPOSITORY_INSTANCE);
    createEAttribute(aptRepositoryInstanceEClass, APT_REPOSITORY_INSTANCE__NAME);
    createEAttribute(aptRepositoryInstanceEClass, APT_REPOSITORY_INSTANCE__KEY_LINK);
    createEAttribute(aptRepositoryInstanceEClass, APT_REPOSITORY_INSTANCE__REPOSITORY_PATH);
    createEAttribute(aptRepositoryInstanceEClass, APT_REPOSITORY_INSTANCE__UPDATE_ROS_DEP);

    stackImplementationDescriptionEClass = createEClass(STACK_IMPLEMENTATION_DESCRIPTION);
    createEAttribute(stackImplementationDescriptionEClass, STACK_IMPLEMENTATION_DESCRIPTION__TYPE);
    createEAttribute(stackImplementationDescriptionEClass, STACK_IMPLEMENTATION_DESCRIPTION__NAME);
    createEAttribute(stackImplementationDescriptionEClass, STACK_IMPLEMENTATION_DESCRIPTION__IMP_ROSMODEL);
    createEAttribute(stackImplementationDescriptionEClass, STACK_IMPLEMENTATION_DESCRIPTION__DESCRIPTION);
    createEAttribute(stackImplementationDescriptionEClass, STACK_IMPLEMENTATION_DESCRIPTION__MODE);
    createEReference(stackImplementationDescriptionEClass, STACK_IMPLEMENTATION_DESCRIPTION__IMPL);

    packageDescriptionEClass = createEClass(PACKAGE_DESCRIPTION);
    createEAttribute(packageDescriptionEClass, PACKAGE_DESCRIPTION__TYPE);
    createEAttribute(packageDescriptionEClass, PACKAGE_DESCRIPTION__NAME);
    createEReference(packageDescriptionEClass, PACKAGE_DESCRIPTION__IMAGE_DESCRIPTION);
    createEReference(packageDescriptionEClass, PACKAGE_DESCRIPTION__REPOSITORY_DESCRIPTION);

    imageDescriptionEClass = createEClass(IMAGE_DESCRIPTION);
    createEReference(imageDescriptionEClass, IMAGE_DESCRIPTION__TYPES);
    createEReference(imageDescriptionEClass, IMAGE_DESCRIPTION__APPILED_IMPLEMENTATIONS);
    createEReference(imageDescriptionEClass, IMAGE_DESCRIPTION__IMAGE_TAGS);

    repositoryDescriptionEClass = createEClass(REPOSITORY_DESCRIPTION);
    createEReference(repositoryDescriptionEClass, REPOSITORY_DESCRIPTION__SPEC);

    repositorySpecEClass = createEClass(REPOSITORY_SPEC);
    createEAttribute(repositorySpecEClass, REPOSITORY_SPEC__NAME);
    createEReference(repositorySpecEClass, REPOSITORY_SPEC__REPOSITORY);

    repositoryEClass = createEClass(REPOSITORY);
    createEAttribute(repositoryEClass, REPOSITORY__TYPE);
    createEAttribute(repositoryEClass, REPOSITORY__PATH);

    ciSettingEClass = createEClass(CI_SETTING);
    createEAttribute(ciSettingEClass, CI_SETTING__TYPE);
    createEAttribute(ciSettingEClass, CI_SETTING__NAME);
    createEReference(ciSettingEClass, CI_SETTING__CI_TYPES);
    createEReference(ciSettingEClass, CI_SETTING__APPLIED_REPOS);
    createEAttribute(ciSettingEClass, CI_SETTING__REQ_BRANCH_PREFIX);
    createEReference(ciSettingEClass, CI_SETTING__CI_PARAMETERS);

    multiMonolithicImplementationNameListEClass = createEClass(MULTI_MONOLITHIC_IMPLEMENTATION_NAME_LIST);
    createEReference(multiMonolithicImplementationNameListEClass, MULTI_MONOLITHIC_IMPLEMENTATION_NAME_LIST__VALUES);

    multiMonolithicImplementationNamePreListEClass = createEClass(MULTI_MONOLITHIC_IMPLEMENTATION_NAME_PRE_LIST);

    multiMonolithicImplementationNameListBracketEClass = createEClass(MULTI_MONOLITHIC_IMPLEMENTATION_NAME_LIST_BRACKET);

    ciParametersEClass = createEClass(CI_PARAMETERS);
    createEAttribute(ciParametersEClass, CI_PARAMETERS__TYPE);
    createEReference(ciParametersEClass, CI_PARAMETERS__PARAMETERS);

    groupedPropertiesEClass = createEClass(GROUPED_PROPERTIES);
    createEAttribute(groupedPropertiesEClass, GROUPED_PROPERTIES__TYPE);
    createEReference(groupedPropertiesEClass, GROUPED_PROPERTIES__PROPERTIES);

    // Create enums
    implementationModeTypeEEnum = createEEnum(IMPLEMENTATION_MODE_TYPE);
    booleanEEnum = createEEnum(BOOLEAN);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    commonPropertySingleValueEClass.getESuperTypes().add(this.getPropertyExpressType());
    commonPropertyMultiValueEClass.getESuperTypes().add(this.getPropertyExpressType());
    multiValueListPreListEClass.getESuperTypes().add(this.getMultiValueList());
    multiValueListBracketEClass.getESuperTypes().add(this.getMultiValueList());
    localPackageEClass.getESuperTypes().add(this.getDependencyTypes());
    gitPackageEClass.getESuperTypes().add(this.getDependencyTypes());
    multiMonolithicImplementationNamePreListEClass.getESuperTypes().add(this.getMultiMonolithicImplementationNameList());
    multiMonolithicImplementationNameListBracketEClass.getESuperTypes().add(this.getMultiMonolithicImplementationNameList());

    // Initialize classes and features; add operations and parameters
    initEClass(yamlEClass, Yaml.class, "Yaml", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYaml_Content(), this.getYamlContent(), null, "content", null, 0, -1, Yaml.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(yamlContentEClass, YamlContent.class, "YamlContent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYamlContent_RootContent(), ecorePackage.getEObject(), null, "rootContent", null, 0, 1, YamlContent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(monolithicImplementationDescriptionEClass, MonolithicImplementationDescription.class, "MonolithicImplementationDescription", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMonolithicImplementationDescription_Type(), ecorePackage.getEString(), "type", null, 0, 1, MonolithicImplementationDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMonolithicImplementationDescription_Name(), ecorePackage.getEString(), "name", null, 0, 1, MonolithicImplementationDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMonolithicImplementationDescription_ImpRosmodel(), ecorePackage.getEString(), "impRosmodel", null, 0, 1, MonolithicImplementationDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMonolithicImplementationDescription_Description(), ecorePackage.getEString(), "description", null, 0, 1, MonolithicImplementationDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMonolithicImplementationDescription_Mode(), this.getImplementationModeType(), "mode", null, 0, 1, MonolithicImplementationDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMonolithicImplementationDescription_Branch(), ecorePackage.getEString(), "branch", null, 0, 1, MonolithicImplementationDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMonolithicImplementationDescription_Implementation(), this.getNewImplementationArtifact(), null, "implementation", null, 0, 1, MonolithicImplementationDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(newImplementationArtifactEClass, NewImplementationArtifact.class, "NewImplementationArtifact", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNewImplementationArtifact_Location(), ecorePackage.getEString(), "location", null, 0, 1, NewImplementationArtifact.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getNewImplementationArtifact_DeployRequirements(), this.getDeploymentRequirements(), null, "deployRequirements", null, 0, 1, NewImplementationArtifact.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getNewImplementationArtifact_ResourceRequirements(), this.getResourceRequirements(), null, "resourceRequirements", null, 0, 1, NewImplementationArtifact.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getNewImplementationArtifact_BuildRequirements(), this.getBuildRequirements(), null, "buildRequirements", null, 0, 1, NewImplementationArtifact.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getNewImplementationArtifact_StartCommands(), this.getMultiValueList(), null, "startCommands", null, 0, 1, NewImplementationArtifact.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(implementationArtifactDescriptionEClass, ImplementationArtifactDescription.class, "ImplementationArtifactDescription", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getImplementationArtifactDescription_Impl(), ecorePackage.getEObject(), null, "impl", null, 0, 1, ImplementationArtifactDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(reuseImplementationArtifactEClass, ReuseImplementationArtifact.class, "ReuseImplementationArtifact", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getReuseImplementationArtifact_Lists(), this.getImplementationArtifactAbstract(), null, "lists", null, 0, -1, ReuseImplementationArtifact.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(implementationArtifactAbstractEClass, ImplementationArtifactAbstract.class, "ImplementationArtifactAbstract", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getImplementationArtifactAbstract_ImportedNamespace(), ecorePackage.getEString(), "importedNamespace", null, 0, 1, ImplementationArtifactAbstract.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImplementationArtifactAbstract_Name(), this.getMonolithicImplementationDescription(), null, "name", null, 0, 1, ImplementationArtifactAbstract.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImplementationArtifactAbstract_StartCommands(), this.getMultiValueList(), null, "startCommands", null, 0, 1, ImplementationArtifactAbstract.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(deploymentRequirementsEClass, DeploymentRequirements.class, "DeploymentRequirements", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeploymentRequirements_Requirements(), this.getPropertyExpressType(), null, "requirements", null, 0, -1, DeploymentRequirements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(resourceRequirementsEClass, ResourceRequirements.class, "ResourceRequirements", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getResourceRequirements_Requirements(), this.getPropertyExpressType(), null, "requirements", null, 0, -1, ResourceRequirements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(propertyExpressTypeEClass, PropertyExpressType.class, "PropertyExpressType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPropertyExpressType_Name(), ecorePackage.getEString(), "name", null, 0, 1, PropertyExpressType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(commonPropertySingleValueEClass, CommonPropertySingleValue.class, "CommonPropertySingleValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCommonPropertySingleValue_Value(), ecorePackage.getEString(), "value", null, 0, 1, CommonPropertySingleValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(commonPropertyMultiValueEClass, CommonPropertyMultiValue.class, "CommonPropertyMultiValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCommonPropertyMultiValue_Value(), this.getMultiValueList(), null, "value", null, 0, 1, CommonPropertyMultiValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(multiValueListEClass, MultiValueList.class, "MultiValueList", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMultiValueList_Values(), ecorePackage.getEString(), "values", null, 0, -1, MultiValueList.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(multiValueListPreListEClass, MultiValueListPreList.class, "MultiValueListPreList", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(multiValueListBracketEClass, MultiValueListBracket.class, "MultiValueListBracket", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(buildRequirementsEClass, BuildRequirements.class, "BuildRequirements", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBuildRequirements_ReqRosDistros(), this.getMultiValueList(), null, "ReqRosDistros", null, 0, 1, BuildRequirements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBuildRequirements_ReqTestRosDistros(), this.getMultiValueList(), null, "ReqTestRosDistros", null, 0, 1, BuildRequirements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBuildRequirements_ReqBuildDependencies(), this.getReqBuildDependencies(), null, "ReqBuildDependencies", null, 0, 1, BuildRequirements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBuildRequirements_ReqDependencyRepositories(), this.getReqDependencyRepositories(), null, "ReqDependencyRepositories", null, 0, 1, BuildRequirements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBuildRequirements_ReqCMakeArgs(), this.getMultiValueList(), null, "ReqCMakeArgs", null, 0, 1, BuildRequirements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(reqBuildDependenciesEClass, ReqBuildDependencies.class, "ReqBuildDependencies", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getReqBuildDependencies_Dependencies(), this.getDependencyTypes(), null, "dependencies", null, 0, -1, ReqBuildDependencies.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dependencyTypesEClass, DependencyTypes.class, "DependencyTypes", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(localPackageEClass, LocalPackage.class, "LocalPackage", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLocalPackage_Name(), this.getMonolithicImplementationDescription(), null, "name", null, 0, 1, LocalPackage.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(gitPackageEClass, GitPackage.class, "GitPackage", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGitPackage_Name(), ecorePackage.getEString(), "name", null, 0, 1, GitPackage.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGitPackage_Path(), ecorePackage.getEString(), "path", null, 0, 1, GitPackage.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGitPackage_Visibility(), ecorePackage.getEString(), "visibility", null, 0, 1, GitPackage.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(reqDependencyRepositoriesEClass, ReqDependencyRepositories.class, "ReqDependencyRepositories", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getReqDependencyRepositories_Children(), this.getAptRepositoryInstance(), null, "children", null, 0, -1, ReqDependencyRepositories.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(aptRepositoryInstanceEClass, AptRepositoryInstance.class, "AptRepositoryInstance", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAptRepositoryInstance_Name(), ecorePackage.getEString(), "name", null, 0, 1, AptRepositoryInstance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAptRepositoryInstance_KeyLink(), ecorePackage.getEString(), "keyLink", null, 0, 1, AptRepositoryInstance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAptRepositoryInstance_RepositoryPath(), ecorePackage.getEString(), "repositoryPath", null, 0, 1, AptRepositoryInstance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAptRepositoryInstance_UpdateRosDep(), ecorePackage.getEString(), "updateRosDep", null, 0, 1, AptRepositoryInstance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stackImplementationDescriptionEClass, StackImplementationDescription.class, "StackImplementationDescription", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStackImplementationDescription_Type(), ecorePackage.getEString(), "type", null, 0, 1, StackImplementationDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStackImplementationDescription_Name(), ecorePackage.getEString(), "name", null, 0, 1, StackImplementationDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStackImplementationDescription_ImpRosmodel(), ecorePackage.getEString(), "impRosmodel", null, 0, 1, StackImplementationDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStackImplementationDescription_Description(), ecorePackage.getEString(), "description", null, 0, 1, StackImplementationDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStackImplementationDescription_Mode(), this.getImplementationModeType(), "mode", null, 0, 1, StackImplementationDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getStackImplementationDescription_Impl(), this.getImplementationArtifactDescription(), null, "impl", null, 0, 1, StackImplementationDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(packageDescriptionEClass, PackageDescription.class, "PackageDescription", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPackageDescription_Type(), ecorePackage.getEString(), "type", null, 0, 1, PackageDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPackageDescription_Name(), ecorePackage.getEString(), "name", null, 0, 1, PackageDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPackageDescription_ImageDescription(), this.getImageDescription(), null, "imageDescription", null, 0, 1, PackageDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPackageDescription_RepositoryDescription(), this.getRepositoryDescription(), null, "repositoryDescription", null, 0, 1, PackageDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imageDescriptionEClass, ImageDescription.class, "ImageDescription", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getImageDescription_Types(), this.getMultiValueList(), null, "types", null, 0, 1, ImageDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImageDescription_AppiledImplementations(), this.getMultiMonolithicImplementationNameList(), null, "appiledImplementations", null, 0, 1, ImageDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getImageDescription_ImageTags(), this.getMultiValueList(), null, "imageTags", null, 0, 1, ImageDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(repositoryDescriptionEClass, RepositoryDescription.class, "RepositoryDescription", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRepositoryDescription_Spec(), this.getRepositorySpec(), null, "spec", null, 0, -1, RepositoryDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(repositorySpecEClass, RepositorySpec.class, "RepositorySpec", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRepositorySpec_Name(), ecorePackage.getEString(), "name", null, 0, 1, RepositorySpec.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRepositorySpec_Repository(), this.getRepository(), null, "repository", null, 0, 1, RepositorySpec.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(repositoryEClass, Repository.class, "Repository", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRepository_Type(), ecorePackage.getEString(), "type", null, 0, 1, Repository.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRepository_Path(), ecorePackage.getEString(), "path", null, 0, 1, Repository.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ciSettingEClass, CISetting.class, "CISetting", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCISetting_Type(), ecorePackage.getEString(), "type", null, 0, 1, CISetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCISetting_Name(), ecorePackage.getEString(), "name", null, 0, 1, CISetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCISetting_CiTypes(), this.getMultiValueList(), null, "ciTypes", null, 0, 1, CISetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCISetting_AppliedRepos(), this.getMultiMonolithicImplementationNameList(), null, "appliedRepos", null, 0, 1, CISetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCISetting_ReqBranchPrefix(), ecorePackage.getEString(), "reqBranchPrefix", null, 0, 1, CISetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCISetting_CiParameters(), this.getCIParameters(), null, "ciParameters", null, 0, -1, CISetting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(multiMonolithicImplementationNameListEClass, MultiMonolithicImplementationNameList.class, "MultiMonolithicImplementationNameList", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMultiMonolithicImplementationNameList_Values(), this.getMonolithicImplementationDescription(), null, "values", null, 0, -1, MultiMonolithicImplementationNameList.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(multiMonolithicImplementationNamePreListEClass, MultiMonolithicImplementationNamePreList.class, "MultiMonolithicImplementationNamePreList", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(multiMonolithicImplementationNameListBracketEClass, MultiMonolithicImplementationNameListBracket.class, "MultiMonolithicImplementationNameListBracket", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(ciParametersEClass, CIParameters.class, "CIParameters", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCIParameters_Type(), ecorePackage.getEString(), "type", null, 0, 1, CIParameters.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCIParameters_Parameters(), this.getGroupedProperties(), null, "parameters", null, 0, -1, CIParameters.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(groupedPropertiesEClass, GroupedProperties.class, "GroupedProperties", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGroupedProperties_Type(), ecorePackage.getEString(), "type", null, 0, 1, GroupedProperties.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGroupedProperties_Properties(), this.getPropertyExpressType(), null, "properties", null, 0, -1, GroupedProperties.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(implementationModeTypeEEnum, ImplementationModeType.class, "ImplementationModeType");
    addEEnumLiteral(implementationModeTypeEEnum, ImplementationModeType.DEBUG_MODE);
    addEEnumLiteral(implementationModeTypeEEnum, ImplementationModeType.RELEASE_MODE);

    initEEnum(booleanEEnum, de.fraunhofer.ipa.deployment.deployModel.BOOLEAN.class, "BOOLEAN");
    addEEnumLiteral(booleanEEnum, de.fraunhofer.ipa.deployment.deployModel.BOOLEAN.FALSE);
    addEEnumLiteral(booleanEEnum, de.fraunhofer.ipa.deployment.deployModel.BOOLEAN.TRUE);

    // Create resource
    createResource(eNS_URI);
  }

} //DeployModelPackageImpl
