/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel.impl;

import de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage;
import de.fraunhofer.ipa.deployment.deployModel.MultiMonolithicImplementationNameListBracket;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Multi Monolithic Implementation Name List Bracket</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MultiMonolithicImplementationNameListBracketImpl extends MultiMonolithicImplementationNameListImpl implements MultiMonolithicImplementationNameListBracket
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MultiMonolithicImplementationNameListBracketImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DeployModelPackage.Literals.MULTI_MONOLITHIC_IMPLEMENTATION_NAME_LIST_BRACKET;
  }

} //MultiMonolithicImplementationNameListBracketImpl
