/*
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.serializer;

import com.google.inject.Inject;
import de.fraunhofer.ipa.deployment.services.DeployModelGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class DeployModelSyntacticSequencer extends AbstractSyntacticSequencer {

	protected DeployModelGrammarAccess grammarAccess;
	protected AbstractElementAlias match_MultiMonolithicImplementationNameListBracket_CommaKeyword_2_0_q;
	protected AbstractElementAlias match_MultiValueListBracket_CommaKeyword_2_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (DeployModelGrammarAccess) access;
		match_MultiMonolithicImplementationNameListBracket_CommaKeyword_2_0_q = new TokenAlias(false, true, grammarAccess.getMultiMonolithicImplementationNameListBracketAccess().getCommaKeyword_2_0());
		match_MultiValueListBracket_CommaKeyword_2_0_q = new TokenAlias(false, true, grammarAccess.getMultiValueListBracketAccess().getCommaKeyword_2_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getDEDENTRule())
			return getDEDENTToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getINDENTRule())
			return getINDENTToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getPreListElementRule())
			return getPreListElementToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * Synthetic terminal rule. The concrete syntax is to be specified by clients.
	 * Defaults to the empty string.
	 */
	protected String getDEDENTToken(EObject semanticObject, RuleCall ruleCall, INode node) { return ""; }
	
	/**
	 * Synthetic terminal rule. The concrete syntax is to be specified by clients.
	 * Defaults to the empty string.
	 */
	protected String getINDENTToken(EObject semanticObject, RuleCall ruleCall, INode node) { return ""; }
	
	/**
	 * PreListElement hidden(SL_COMMENT):
	 *   '-';
	 */
	protected String getPreListElementToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "-";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_MultiMonolithicImplementationNameListBracket_CommaKeyword_2_0_q.equals(syntax))
				emit_MultiMonolithicImplementationNameListBracket_CommaKeyword_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_MultiValueListBracket_CommaKeyword_2_0_q.equals(syntax))
				emit_MultiValueListBracket_CommaKeyword_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     values+=[MonolithicImplementationDescription|QualifiedName] (ambiguity) ']' (rule end)
	 
	 * </pre>
	 */
	protected void emit_MultiMonolithicImplementationNameListBracket_CommaKeyword_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     values+=ValueTypes (ambiguity) ']' (rule end)
	 
	 * </pre>
	 */
	protected void emit_MultiValueListBracket_CommaKeyword_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
