@startuml (id=SingleImplementationArtifactDescription)
!include NamedImplementationArtifact.wsd!NamedImplementationArtifact
class SingleImplementationArtifactDescription

SingleImplementationArtifactDescription --> NamedImplementationArtifact

@enduml