@startuml (id=StackImplementationArtifactDescription)

!include NamedImplementationArtifact.wsd!NamedImplementationArtifact
class StackImplementationArtifactDescription

StackImplementationArtifactDescription *--> NamedImplementationArtifact
@enduml
