/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dependency Types</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getDependencyTypes()
 * @model
 * @generated
 */
public interface DependencyTypes extends EObject
{
} // DependencyTypes
