/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Grouped Properties</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.GroupedProperties#getType <em>Type</em>}</li>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.GroupedProperties#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getGroupedProperties()
 * @model
 * @generated
 */
public interface GroupedProperties extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getGroupedProperties_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link de.fraunhofer.ipa.deployment.deployModel.GroupedProperties#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link de.fraunhofer.ipa.deployment.deployModel.PropertyExpressType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getGroupedProperties_Properties()
   * @model containment="true"
   * @generated
   */
  EList<PropertyExpressType> getProperties();

} // GroupedProperties
