/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Image Version Types</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getImageVersionTypes()
 * @model
 * @generated
 */
public enum ImageVersionTypes implements Enumerator
{
  /**
   * The '<em><b>Branch</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BRANCH_VALUE
   * @generated
   * @ordered
   */
  BRANCH(0, "branch", "branch"),

  /**
   * The '<em><b>Commit Hash</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COMMIT_HASH_VALUE
   * @generated
   * @ordered
   */
  COMMIT_HASH(1, "commitHash", "commit"),

  /**
   * The '<em><b>Latest</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LATEST_VALUE
   * @generated
   * @ordered
   */
  LATEST(2, "latest", "latest"),

  /**
   * The '<em><b>Release</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RELEASE_VALUE
   * @generated
   * @ordered
   */
  RELEASE(3, "release", "release");

  /**
   * The '<em><b>Branch</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BRANCH
   * @model name="branch"
   * @generated
   * @ordered
   */
  public static final int BRANCH_VALUE = 0;

  /**
   * The '<em><b>Commit Hash</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COMMIT_HASH
   * @model name="commitHash" literal="commit"
   * @generated
   * @ordered
   */
  public static final int COMMIT_HASH_VALUE = 1;

  /**
   * The '<em><b>Latest</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LATEST
   * @model name="latest"
   * @generated
   * @ordered
   */
  public static final int LATEST_VALUE = 2;

  /**
   * The '<em><b>Release</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RELEASE
   * @model name="release"
   * @generated
   * @ordered
   */
  public static final int RELEASE_VALUE = 3;

  /**
   * An array of all the '<em><b>Image Version Types</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ImageVersionTypes[] VALUES_ARRAY =
    new ImageVersionTypes[]
    {
      BRANCH,
      COMMIT_HASH,
      LATEST,
      RELEASE,
    };

  /**
   * A public read-only list of all the '<em><b>Image Version Types</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ImageVersionTypes> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Image Version Types</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ImageVersionTypes get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ImageVersionTypes result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Image Version Types</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ImageVersionTypes getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ImageVersionTypes result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Image Version Types</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ImageVersionTypes get(int value)
  {
    switch (value)
    {
      case BRANCH_VALUE: return BRANCH;
      case COMMIT_HASH_VALUE: return COMMIT_HASH;
      case LATEST_VALUE: return LATEST;
      case RELEASE_VALUE: return RELEASE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ImageVersionTypes(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ImageVersionTypes
