/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Image Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.ImageDescription#getTypes <em>Types</em>}</li>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.ImageDescription#getName <em>Name</em>}</li>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.ImageDescription#getImageVersions <em>Image Versions</em>}</li>
 * </ul>
 *
 * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getImageDescription()
 * @model
 * @generated
 */
public interface ImageDescription extends EObject
{
  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference list.
   * The list contents are of type {@link de.fraunhofer.ipa.deployment.deployModel.ImageTypeList}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference list.
   * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getImageDescription_Types()
   * @model containment="true"
   * @generated
   */
  EList<ImageTypeList> getTypes();

  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(MonolithicImplementationDescription)
   * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getImageDescription_Name()
   * @model
   * @generated
   */
  MonolithicImplementationDescription getName();

  /**
   * Sets the value of the '{@link de.fraunhofer.ipa.deployment.deployModel.ImageDescription#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(MonolithicImplementationDescription value);

  /**
   * Returns the value of the '<em><b>Image Versions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Image Versions</em>' containment reference.
   * @see #setImageVersions(ImageVersionList)
   * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getImageDescription_ImageVersions()
   * @model containment="true"
   * @generated
   */
  ImageVersionList getImageVersions();

  /**
   * Sets the value of the '{@link de.fraunhofer.ipa.deployment.deployModel.ImageDescription#getImageVersions <em>Image Versions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Image Versions</em>' containment reference.
   * @see #getImageVersions()
   * @generated
   */
  void setImageVersions(ImageVersionList value);

} // ImageDescription
