/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Image Type List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.ImageTypeList#getChildren <em>Children</em>}</li>
 * </ul>
 *
 * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getImageTypeList()
 * @model
 * @generated
 */
public interface ImageTypeList extends EObject
{
  /**
   * Returns the value of the '<em><b>Children</b></em>' attribute list.
   * The list contents are of type {@link de.fraunhofer.ipa.deployment.deployModel.ImageTypes}.
   * The literals are from the enumeration {@link de.fraunhofer.ipa.deployment.deployModel.ImageTypes}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Children</em>' attribute list.
   * @see de.fraunhofer.ipa.deployment.deployModel.ImageTypes
   * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getImageTypeList_Children()
   * @model unique="false"
   * @generated
   */
  EList<ImageTypes> getChildren();

} // ImageTypeList
