/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multi Monolithic Implementation Name List Bracket</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getMultiMonolithicImplementationNameListBracket()
 * @model
 * @generated
 */
public interface MultiMonolithicImplementationNameListBracket extends MultiMonolithicImplementationNameList
{
} // MultiMonolithicImplementationNameListBracket
