/**
 * generated by Xtext 2.27.0
 */
package de.fraunhofer.ipa.deployment.deployModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>New Implementation Artifact</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.NewImplementationArtifact#getName <em>Name</em>}</li>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.NewImplementationArtifact#getDeployRequirements <em>Deploy Requirements</em>}</li>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.NewImplementationArtifact#getResourceRequirements <em>Resource Requirements</em>}</li>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.NewImplementationArtifact#getBuildRequirements <em>Build Requirements</em>}</li>
 *   <li>{@link de.fraunhofer.ipa.deployment.deployModel.NewImplementationArtifact#getStartCommands <em>Start Commands</em>}</li>
 * </ul>
 *
 * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getNewImplementationArtifact()
 * @model
 * @generated
 */
public interface NewImplementationArtifact extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getNewImplementationArtifact_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.fraunhofer.ipa.deployment.deployModel.NewImplementationArtifact#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Deploy Requirements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Deploy Requirements</em>' containment reference.
   * @see #setDeployRequirements(DeploymentRequirements)
   * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getNewImplementationArtifact_DeployRequirements()
   * @model containment="true"
   * @generated
   */
  DeploymentRequirements getDeployRequirements();

  /**
   * Sets the value of the '{@link de.fraunhofer.ipa.deployment.deployModel.NewImplementationArtifact#getDeployRequirements <em>Deploy Requirements</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Deploy Requirements</em>' containment reference.
   * @see #getDeployRequirements()
   * @generated
   */
  void setDeployRequirements(DeploymentRequirements value);

  /**
   * Returns the value of the '<em><b>Resource Requirements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource Requirements</em>' containment reference.
   * @see #setResourceRequirements(ResourceRequirements)
   * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getNewImplementationArtifact_ResourceRequirements()
   * @model containment="true"
   * @generated
   */
  ResourceRequirements getResourceRequirements();

  /**
   * Sets the value of the '{@link de.fraunhofer.ipa.deployment.deployModel.NewImplementationArtifact#getResourceRequirements <em>Resource Requirements</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource Requirements</em>' containment reference.
   * @see #getResourceRequirements()
   * @generated
   */
  void setResourceRequirements(ResourceRequirements value);

  /**
   * Returns the value of the '<em><b>Build Requirements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Build Requirements</em>' containment reference.
   * @see #setBuildRequirements(BuildRequirements)
   * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getNewImplementationArtifact_BuildRequirements()
   * @model containment="true"
   * @generated
   */
  BuildRequirements getBuildRequirements();

  /**
   * Sets the value of the '{@link de.fraunhofer.ipa.deployment.deployModel.NewImplementationArtifact#getBuildRequirements <em>Build Requirements</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Build Requirements</em>' containment reference.
   * @see #getBuildRequirements()
   * @generated
   */
  void setBuildRequirements(BuildRequirements value);

  /**
   * Returns the value of the '<em><b>Start Commands</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Commands</em>' containment reference.
   * @see #setStartCommands(StartCommands)
   * @see de.fraunhofer.ipa.deployment.deployModel.DeployModelPackage#getNewImplementationArtifact_StartCommands()
   * @model containment="true"
   * @generated
   */
  StartCommands getStartCommands();

  /**
   * Sets the value of the '{@link de.fraunhofer.ipa.deployment.deployModel.NewImplementationArtifact#getStartCommands <em>Start Commands</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Commands</em>' containment reference.
   * @see #getStartCommands()
   * @generated
   */
  void setStartCommands(StartCommands value);

} // NewImplementationArtifact
